parameters:
#    frontal.example.class: M2c\FrontalBundle\Example

services:
#    frontal.example:
#        class: %frontal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
